#!/bin/bash

# https://github.com/maxtsepkov/bash_colors/blob/master/bash_colors.sh
uncolorize () { sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g" }
if [[ $- != *i* ]]
   then say() { echo -ne $1;echo -e $nocolor; }
		# Colors, yo!
		green="\e[1;32m"
		red="\e[1;31m"
		blue="\e[1;34m"
		purple="\e[1;35m"
		cyan="\e[1;36m"
		nocolor="\e[0m"
   else
		# do nothing
		say() { true; }
fi


export PATH="/root/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

datasets=`mktemp /tmp/datasets.XXXXXX`
zfs list -t snap -r -H tank -o name |grep @ > ${datasets}

for snap in "$@";do
	for dataset in `grep @.*${snap}.*$ ${datasets}`;do
		say "$green ${dataset}"
		zfs destroy ${dataset}
	done
done

rm ${datasets}
